/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-09 08:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class delete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	// detail.jsp 에서 [삭제]를 누르면 get방식으로 이동
	//=> http://localhost:9090/Herbmall/board/delete.jsp?no=3
	//1
	String no = request.getParameter("no");
	if(no == null || no.isEmpty()){
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"잘못된 url입니다.\");\r\n");
      out.write("\t\t\tlocation.href = \"list.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
	return;
	}
	//2
	
	//3


      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>자유게시판 글 삭제 - 허브몰</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mainstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/clear.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/formLayout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tpadding:5px;\r\n");
      out.write("\t\tmargin:5px;\r\n");
      out.write("\t }\r\n");
      out.write("\t.divForm{\r\n");
      out.write("\t\twidth:650px;\r\n");
      out.write("\t\tborder:1px solid #ddd;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t/* .divForm form{\r\n");
      out.write("\t\twidth:650px;\r\n");
      out.write("\t} */\r\n");
      out.write("\t.divForm div\t{\r\n");
      out.write("\t\t/* clear: both; */\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tpadding: 7px 0;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t.sp{\r\n");
      out.write("\t\tfont-size:0.9em;\r\n");
      out.write("\t\tcolor:#0056AC;\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.divForm fieldset\t{\r\n");
      out.write("\t\tborder:0;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"form[name=frmDelete]\").submit(function() {\r\n");
      out.write("\t\t\tvar pwd = $(\"input[name=pwd]\").val();\r\n");
      out.write("\t\t\tif(pwd == ''){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하셔야 합니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"divForm\">\r\n");
      out.write("<form name=\"frmDelete\" method=\"post\"\taction=\"delete_ok.jsp\" >\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"no\" value=\"");
      out.print( no);
      out.write("\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>글 삭제</legend>\r\n");
      out.write("\t        <div>           \r\n");
      out.write("\t        \t<span class=\"sp\">");
      out.print(no );
      out.write("번 글을 삭제하시겠습니까?</span>                        \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div>           \r\n");
      out.write("\t            <label for=\"pwd\">비밀번호</label>\r\n");
      out.write("\t            <input type=\"password\" id=\"pwd\" name=\"pwd\" />   \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"center\">\r\n");
      out.write("\t            <input type =\"submit\"  value=\"삭제\" />\r\n");
      out.write("\t            <input type = \"Button\" value=\"글목록\" \r\n");
      out.write("                \tOnClick=\"location.href='list.jsp'\" />\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </fieldset>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
