/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-09 07:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import com.herbmall.board.model.BoardVo;
import java.sql.SQLException;
import com.herbmall.board.model.boardDAO;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.herbmall.board.model.BoardVo");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.herbmall.board.model.boardDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// countUpdate.jsp 에서 조회수를 증가시키면 get방식으로 이동
	//=> http://localhost:9090/Herbmall/board/countUpdate.jsp?no=3
	
	// 1.
	String no = request.getParameter("no");
	
	if(no.isEmpty() || no == null){
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javacript\">\r\n");
      out.write("\t\t\talert(\"잘못된 url입니다.\");\r\n");
      out.write("\t\t\tlocation.href=\"list.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");
return;
	}
	// 2.
	boardDAO dao = new boardDAO();
	BoardVo vo = new BoardVo();
	try{
		vo = dao.selectByNo(Integer.parseInt(no));
	}catch(SQLException e){
		e.printStackTrace();
	}
	
	// 3.
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	String content = vo.getContent();
	if(content == null || content.isEmpty()){
		content = "";
	}else{
		content = content.replace("\r\n", "<br>");
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>자유게시판 상세보기 - 허브몰</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mainstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/clear.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/formLayout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tpadding:5px;\r\n");
      out.write("\t\tmargin:5px;\r\n");
      out.write("\t }\r\n");
      out.write("\t.divForm {\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\t}\r\n");
      out.write("</style>  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>글 상세보기</h2>\r\n");
      out.write("\t<div class=\"divForm\">\r\n");
      out.write("\t\t<div class=\"firstDiv\">\r\n");
      out.write("\t\t\t<span class=\"sp1\">제목</span> <span>");
      out.print(vo.getTitle() );
      out.write("</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"sp1\">작성자</span> <span>");
      out.print( vo.getName() );
      out.write("</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"sp1\">등록일</span> <span>");
      out.print( sdf.format(vo.getRegdate()) );
      out.write("</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"sp1\">조회수</span> <span>");
      out.print( vo.getReadcount() );
      out.write("</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"lastDiv\">\t\t\t\r\n");
      out.write("\t\t\t<p class=\"content\">");
      out.print( content );
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t<a href='edit.jsp?no=");
      out.print( vo.getNo());
      out.write("'>수정</a> |\r\n");
      out.write("        \t<a href='delete.jsp?no=");
      out.print( vo.getNo());
      out.write("'>삭제</a> |\r\n");
      out.write("        \t<a href='list.jsp'>목록</a>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
